# Generated by Django 5.2.11 on 2026-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField()),
                ('price', models.IntegerField()),
                ('Quantity', models.CharField()),
                ('Description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=10)),
            ],
        ),
    ]
