# Generated by Django 5.2.11 on 2026-02-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
