# Generated by Django 5.2.11 on 2026-02-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_rename_quantity_productdetails_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='prod_image',
            new_name='image',
        ),
    ]
