# Generated by Django 5.2.9 on 2026-02-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_rename_description_productdetails_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
