# Generated by Django 5.2.9 on 2026-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_remove_user_role_alter_productdetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
