# Generated by Django 5.2.9 on 2026-02-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0011_remove_productdetails_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
