# Generated by Django 6.1.1 on 2026-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0018_userprofile_city_userprofile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
